
program_name = (('ADMINISTRACIÓN DE EMPRESAS'),('ESTUDIOS POLÍTICOS Y RESOLUCIÓN DE CONFLICTOS'),
	            ('LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN MATEMÁTICAS'),
	            ('LICENCIATURA EN CIENCIAS SOCIALES'),('MEDICINA'),('LICENCIATURA EN EDUCACIÓN FÍSICA Y DEPORTE'),
	            ('LICENCIATURA EN LENGUAS EXTRANJERAS INGLÉS - FRANCÉS'),('ECONOMÍA'),
	            ('INGENIERÍA DE MATERIALES'),('RECREACIÓN'),('CONTADURÍA PÚBLICA'),
               ('FONOAUDIOLOGÍA'),('INGENIERÍA INDUSTRIAL'),('LICENCIATURA EN EDUCACIÓN POPULAR'),('FÍSICA'),
               ('LICENCIATURA EN LITERATURA'),('LICENCIATURA EN FILOSOFÍA'),('ARQUITECTURA'),('TRABAJO SOCIAL'),
               ('INGENIERÍA AGRÍCOLA'),('DISEÑO GRÁFICO'),('INGENIERÍA ELECTRÓNICA'),('GEOGRAFÍA'),
               ('INGENIERÍA QUÍMICA'),('INGENIERÍA CIVIL'),('PROFESIONAL EN FILOSOFÍA'),('INGENIERÍA TOPOGRAFICA'),
               ('DISEÑO INDUSTRIAL'),('QUÍMICA'),('LICENCIATURA EN LENGUAS EXTRANJERAS CON ÉNFASIS EN INGLÉS Y FRANCÉS'),
               ('INGENIERÍA DE SISTEMAS'),('LICENCIATURA EN MATEMÁTICAS'),('FISIOTERAPIA'),('ADMINISTRACIÓN PÚBLICA'),
               ('TECNOLOGÍA EN ATENCIÓN PREHOSPITALARIA'),('ESTADÍSTICA'),('LICENCIATURA EN EDUCACIÓN FÍSICA Y DEPORTES'),
               ('LICENCIATURA EN HISTORIA'),('HISTORIA'),('TERAPIA OCUPACIONAL'),('INGENIERÍA MECÁNICA'),('BIOLOGÍA'),
               ('MÚSICA'),('PSICOLOGÍA'),('TECNOLOGÍA QUÍMICA'),('INGENIERÍA ELÉCTRICA'),('SOCIOLOGÍA'),
               ('LICENCIATURA EN ARTES VISUALES'),('LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN CIENCIAS SOCIALES'),
               ('TECNOLOGÍA EN MANEJO Y CONSERVACIÓN DE SUELOS Y AGUAS'),('COMUNICACIÓN SOCIAL'),('INGENIERÍA DE ALIMENTOS'),
               ('LICENCIATURA EN DANZA CLÁSICA'),('LICENCIATURA EN MÚSICA'),('INGENIERÍA SANITARIA Y AMBIENTAL'),
               ('LICENCIATURA EN ARTE DRAMÁTICO'),('TECNOLOGÍA EN INTERPRETACIÓN PARA SORDOS Y SORDOCIEGOS'))


"""
Genera un conjunto de tuplas. La primera minicula y la segunda mayuscula
"""
def convert_tuple(tuple_n,name_file = ''):
     tuple_new = []
     for i in tuple_n:
          tuple_new.append((i.lower(),i))
     tuple_new = tuple(tuple_new)

     with open(name_file + '.txt','w') as f:
          f.writelines(str(tuple_new))

convert_tuple(program_name,'program_n')



